#!/bin/bash
python /Users/huanxin/data_fetching/lender_total.py 0 64 &
python /Users/huanxin/data_fetching/lender_total.py 1 64 &
python /Users/huanxin/data_fetching/lender_total.py 2 64 &
python /Users/huanxin/data_fetching/lender_total.py 3 64 &
python /Users/huanxin/data_fetching/lender_total.py 4 64 &
python /Users/huanxin/data_fetching/lender_total.py 5 64 &
python /Users/huanxin/data_fetching/lender_total.py 6 64 &
python /Users/huanxin/data_fetching/lender_total.py 7 64 &
python /Users/huanxin/data_fetching/lender_total.py 8 64 &
python /Users/huanxin/data_fetching/lender_total.py 9 64 &
python /Users/huanxin/data_fetching/lender_total.py 10 64 &
python /Users/huanxin/data_fetching/lender_total.py 11 64 &
python /Users/huanxin/data_fetching/lender_total.py 12 64 &
python /Users/huanxin/data_fetching/lender_total.py 13 64 &
python /Users/huanxin/data_fetching/lender_total.py 14 64 &
python /Users/huanxin/data_fetching/lender_total.py 15 64 &
python /Users/huanxin/data_fetching/lender_total.py 16 64 &
python /Users/huanxin/data_fetching/lender_total.py 17 64 &
python /Users/huanxin/data_fetching/lender_total.py 18 64 &
python /Users/huanxin/data_fetching/lender_total.py 19 64 &
python /Users/huanxin/data_fetching/lender_total.py 20 64 &
python /Users/huanxin/data_fetching/lender_total.py 21 64 &
python /Users/huanxin/data_fetching/lender_total.py 22 64 &
python /Users/huanxin/data_fetching/lender_total.py 23 64 &
python /Users/huanxin/data_fetching/lender_total.py 24 64 &
python /Users/huanxin/data_fetching/lender_total.py 25 64 &
python /Users/huanxin/data_fetching/lender_total.py 26 64 &
python /Users/huanxin/data_fetching/lender_total.py 27 64 &
python /Users/huanxin/data_fetching/lender_total.py 28 64 &
python /Users/huanxin/data_fetching/lender_total.py 29 64 &
python /Users/huanxin/data_fetching/lender_total.py 30 64 &
python /Users/huanxin/data_fetching/lender_total.py 31 64 &
python /Users/huanxin/data_fetching/lender_total.py 32 64 &
python /Users/huanxin/data_fetching/lender_total.py 33 64 &
python /Users/huanxin/data_fetching/lender_total.py 34 64 &
python /Users/huanxin/data_fetching/lender_total.py 35 64 &
python /Users/huanxin/data_fetching/lender_total.py 36 64 &
python /Users/huanxin/data_fetching/lender_total.py 37 64 &
python /Users/huanxin/data_fetching/lender_total.py 38 64 &
python /Users/huanxin/data_fetching/lender_total.py 39 64 &
python /Users/huanxin/data_fetching/lender_total.py 40 64 &
python /Users/huanxin/data_fetching/lender_total.py 41 64 &
python /Users/huanxin/data_fetching/lender_total.py 42 64 &
python /Users/huanxin/data_fetching/lender_total.py 43 64 &
python /Users/huanxin/data_fetching/lender_total.py 44 64 &
python /Users/huanxin/data_fetching/lender_total.py 45 64 &
python /Users/huanxin/data_fetching/lender_total.py 46 64 &
python /Users/huanxin/data_fetching/lender_total.py 47 64 &
python /Users/huanxin/data_fetching/lender_total.py 48 64 &
python /Users/huanxin/data_fetching/lender_total.py 49 64 &
python /Users/huanxin/data_fetching/lender_total.py 50 64 &
python /Users/huanxin/data_fetching/lender_total.py 51 64 &
python /Users/huanxin/data_fetching/lender_total.py 52 64 &
python /Users/huanxin/data_fetching/lender_total.py 53 64 &
python /Users/huanxin/data_fetching/lender_total.py 54 64 &
python /Users/huanxin/data_fetching/lender_total.py 55 64 &
python /Users/huanxin/data_fetching/lender_total.py 56 64 &
python /Users/huanxin/data_fetching/lender_total.py 57 64 &
python /Users/huanxin/data_fetching/lender_total.py 58 64 &
python /Users/huanxin/data_fetching/lender_total.py 59 64 &
python /Users/huanxin/data_fetching/lender_total.py 60 64 &
python /Users/huanxin/data_fetching/lender_total.py 61 64 &
python /Users/huanxin/data_fetching/lender_total.py 62 64 &
python /Users/huanxin/data_fetching/lender_total.py 63 64 &
