#!/bin/bash
python /Users/huanxin/data_fetching/lender_main.py 0 64 &
python /Users/huanxin/data_fetching/lender_main.py 1 64 &
python /Users/huanxin/data_fetching/lender_main.py 2 64 &
python /Users/huanxin/data_fetching/lender_main.py 3 64 &
python /Users/huanxin/data_fetching/lender_main.py 4 64 &
python /Users/huanxin/data_fetching/lender_main.py 5 64 &
python /Users/huanxin/data_fetching/lender_main.py 6 64 &
python /Users/huanxin/data_fetching/lender_main.py 7 64 &
python /Users/huanxin/data_fetching/lender_main.py 8 64 &
python /Users/huanxin/data_fetching/lender_main.py 9 64 &
python /Users/huanxin/data_fetching/lender_main.py 10 64 &
python /Users/huanxin/data_fetching/lender_main.py 11 64 &
python /Users/huanxin/data_fetching/lender_main.py 12 64 &
python /Users/huanxin/data_fetching/lender_main.py 13 64 &
python /Users/huanxin/data_fetching/lender_main.py 14 64 &
python /Users/huanxin/data_fetching/lender_main.py 15 64 &
python /Users/huanxin/data_fetching/lender_main.py 16 64 &
python /Users/huanxin/data_fetching/lender_main.py 17 64 &
python /Users/huanxin/data_fetching/lender_main.py 18 64 &
python /Users/huanxin/data_fetching/lender_main.py 19 64 &
python /Users/huanxin/data_fetching/lender_main.py 20 64 &
python /Users/huanxin/data_fetching/lender_main.py 21 64 &
python /Users/huanxin/data_fetching/lender_main.py 22 64 &
python /Users/huanxin/data_fetching/lender_main.py 23 64 &
python /Users/huanxin/data_fetching/lender_main.py 24 64 &
python /Users/huanxin/data_fetching/lender_main.py 25 64 &
python /Users/huanxin/data_fetching/lender_main.py 26 64 &
python /Users/huanxin/data_fetching/lender_main.py 27 64 &
python /Users/huanxin/data_fetching/lender_main.py 28 64 &
python /Users/huanxin/data_fetching/lender_main.py 29 64 &
python /Users/huanxin/data_fetching/lender_main.py 30 64 &
python /Users/huanxin/data_fetching/lender_main.py 31 64 &
python /Users/huanxin/data_fetching/lender_main.py 32 64 &
python /Users/huanxin/data_fetching/lender_main.py 33 64 &
python /Users/huanxin/data_fetching/lender_main.py 34 64 &
python /Users/huanxin/data_fetching/lender_main.py 35 64 &
python /Users/huanxin/data_fetching/lender_main.py 36 64 &
python /Users/huanxin/data_fetching/lender_main.py 37 64 &
python /Users/huanxin/data_fetching/lender_main.py 38 64 &
python /Users/huanxin/data_fetching/lender_main.py 39 64 &
python /Users/huanxin/data_fetching/lender_main.py 40 64 &
python /Users/huanxin/data_fetching/lender_main.py 41 64 &
python /Users/huanxin/data_fetching/lender_main.py 42 64 &
python /Users/huanxin/data_fetching/lender_main.py 43 64 &
python /Users/huanxin/data_fetching/lender_main.py 44 64 &
python /Users/huanxin/data_fetching/lender_main.py 45 64 &
python /Users/huanxin/data_fetching/lender_main.py 46 64 &
python /Users/huanxin/data_fetching/lender_main.py 47 64 &
python /Users/huanxin/data_fetching/lender_main.py 48 64 &
python /Users/huanxin/data_fetching/lender_main.py 49 64 &
python /Users/huanxin/data_fetching/lender_main.py 50 64 &
python /Users/huanxin/data_fetching/lender_main.py 51 64 &
python /Users/huanxin/data_fetching/lender_main.py 52 64 &
python /Users/huanxin/data_fetching/lender_main.py 53 64 &
python /Users/huanxin/data_fetching/lender_main.py 54 64 &
python /Users/huanxin/data_fetching/lender_main.py 55 64 &
python /Users/huanxin/data_fetching/lender_main.py 56 64 &
python /Users/huanxin/data_fetching/lender_main.py 57 64 &
python /Users/huanxin/data_fetching/lender_main.py 58 64 &
python /Users/huanxin/data_fetching/lender_main.py 59 64 &
python /Users/huanxin/data_fetching/lender_main.py 60 64 &
python /Users/huanxin/data_fetching/lender_main.py 61 64 &
python /Users/huanxin/data_fetching/lender_main.py 62 64 &
python /Users/huanxin/data_fetching/lender_main.py 63 64 &
